# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOgnCCj2gQuQhfVkLWF777g0remIO_h-
"""

import math
from collections import Counter

point = ['a','b','c','c','d']
x1 = [7,8,5,9]
x2 = [2,1,4,6]
labels = ['pos','neg','pos','neg']
p = [8,2]
k = 3

dataset = []


for i in range(min(len(point), len(x1), len(x2))):
  dist = math.sqrt(((p[0]-x1[i])**2)+(p[1]-x2[i])**2)
  print(point[i],dist)
  dataset.append({'name':point[i],'dist':dist,'label':labels[i]})

dataset.sort(key = lambda x:x['dist'])

neighbor = dataset[:k]

neighbor_labels = [n['label']for n in neighbor]
prediction = Counter(neighbor_labels).most_common(1)[0][0]

print(f"Target point p{p} Results:")
print("-"*30)
for n in neighbor:
  print(f"Neighbor{n['name']}:Distance {n['dist']:.2f}, Class: {n['label']}")
print("-"*30)
print(f"Prediction for : {prediction}")